name: Build and deploy Eurus

on: [push]
# Uncomment below after initial check
#   push:
#     branches: 
#       - master
#     paths:
#       - 'eurus/*'

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: install sqlite3
<<<<<<< Updated upstream
      run: sudo apt-get update && sudo apt-get install sqlite3
=======
      run: sudo apt-get update && sudo apt-get install sqlite3 libsqlite3-dev
>>>>>>> Stashed changes
    - name: run all tests
      working-directory: eurus
      run: cargo test 
  
  build-prod:
    runs-on: ubuntu-18.04
    needs: test
    steps:
    - uses: actions/checkout@v1
    - name: install sqlite3
      run: sudo apt-get update && sudo apt-get install sqlite3
    - name: build
      working-directory: eurus
      run: cargo build --release
    - name: upload compilation artifact
      uses: actions/upload-artifact@v1
      with:
        name: artifacts
        path: eurus/target/release/eurus
  
  # deploy:
  #   runs-on: ubuntu-18.04
  #   needs: [test, build-prod]
  #   steps:
      
