name: Build and deploy Eurus

on: [push]
# Uncomment below after initial check
#   push:
#     branches: 
#       - master
#     paths:
#       - 'eurus/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build prod
      run: cargo build --release
    - name: Run tests
      run: cargo test
#     - name: Deploy
#       run: TODO
