name: Build and deploy Eurus

on: [push]
# Uncomment below after initial check
#   push:
#     branches: 
#       - master
#     paths:
#       - 'eurus/*'

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: run all tests
      run: cargo test 
  
  build-prod:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: install sqlite3
      run: sudo apt-get update && sudo apt-get install sqlite3
    - name: build prod
      run: cd eurus && cargo build --release
    - name: upload compilation artifact
      uses: actions/upload-artifact@v1
      with:
        name: artifacts
        path: cd eurus/target/release/eurus
  # deploy:
  #   runs-on: ubuntu-latest
