name: Build and deploy Eurus

on: [push]
# Uncomment below after initial check
#   push:
#     branches: 
#       - master
#     paths:
#       - 'eurus/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: cd to eurus
      run: cd eurus
    - name: build prod
      run: cargo build --release
  # test:
  #   runs-on: ubuntu-latest
  # deploy:
  #   runs-on: ubuntu-latest
