name: Build and deploy Eurus

on: [push]
# Uncomment below after initial check
#   push:
#     branches: 
#       - master
#     paths:
#       - 'eurus/*'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: install sqlite3
      run: sudo apt-get update && sudo apt-get install sqlite3
    - name: build prod
      run: cd eurus && cargo build --release
  # test:
  #   runs-on: ubuntu-latest
  # deploy:
  #   runs-on: ubuntu-latest
