name: Build and deploy Eurus

on: [push]
# Uncomment below after initial check
#   push:
#     branches: 
#       - master
#     paths:
#       - 'eurus/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    # - name: list
    #   working-directory: ${{ github.workspace }}
    #   run: ls -la
    - name: build prod
      run: cd eurus && cargo build --release
  # test:
  #   runs-on: ubuntu-latest
  # deploy:
  #   runs-on: ubuntu-latest
